### PR TITLE
tools/scylla-nodetool: add restore integration

### PR DESCRIPTION
**Pull request by tchaikov**
as we have an API for restore a keyspace / table, let's expose this feature with nodetool. so we can exercise it without the help of scylla-manager or 3rd-party tools with a user-friendly interface.

in this change:

* add a new subcommand named "restore" to nodetool
* add test to verify its interaction with the API server
* update the document accordingly.
* the bash completion script is updated accordingly.

### CODE REVIEW

**Comment by tchaikov** [comment]
@xemul hi Pavel, could you please help review this change?

**Comment by denesb** [comment]
Isn't this API added by https://github.com/scylladb/scylladb/pull/20149?

**Comment by tchaikov** [comment]
yes, that's why i am targeting Pavel's fork.

**Comment by tchaikov** [comment]
@xemul ping?

**Comment by tchaikov** [comment]
i will reopen this same PR in kreuzerkrieg's repo

**Pull request closed without merging**
